version: '3.8'

services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - postgres_postgres_1
    ports:
      - "8001:8001"
        #    depends_on:
        # - postgres

#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    networks:
#      - postgres_default

networks:
  postgres_postgres_1:
    driver: bridge

